name: isave
description: Instagram downloader.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  permission_handler: ^8.1.4+2
  path_provider: ^2.0.8
  url_launcher: ^6.0.10
  dio: ^4.0.0
  share_plus: ^3.0.4
  flutter_svg: ^1.0.0
  provider: ^6.0.2
  video_player: ^2.2.10
  flutter_downloader: ^1.7.1
  image_picker: ^0.8.4+4
  reorderable_grid_view: ^2.2.2
  package_info_plus: ^1.3.0
  connectivity_plus: ^2.2.0
  flutter_local_notifications: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.3
  flutter_lints: ^1.0.4

  # The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/images/logo.png"
  image_dark: "assets/images/logo_dark.png"
  android: true
